# Generated by Django 2.1.7 on 2019-03-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('output', models.TextField()),
                ('code', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'interactions',
            },
        ),
    ]
